export type PixelSprite = string[];

export const COLOR_MAP: Record<string, string> = {
  // Skin
  "S": "#ffdbac", "s": "#e0ac69", "X": "#8d5524",
  // Hair/Wood
  "h": "#634e34", "H": "#3b2e1e",
  // Red/Pink
  "R": "#ff4d4d", "r": "#cc0000", "p": "#ff73a8",
  // Blue/Cyan
  "B": "#0099ff", "b": "#0066cc", "C": "#73f2ff",
  // Purple
  "P": "#9933ff", "V": "#6600cc",
  // White/Gray
  "W": "#ffffff", "G": "#cccccc", "g": "#888888", "A": "#444444",
  // Yellow/Gold
  "Y": "#ffff4d", "O": "#ffcc00",
  // Black/Dark
  "K": "#1a1a1a", "k": "#0d0d0d",
  // Green
  "L": "#80ff80", "l": "#4da64d",
  // Brown/Dark Red
  "D": "#8c4646", "d": "#592d2d",
  // Glass/Ice (Semi-transparent visual via lighter colors)
  "I": "#e6f7ff", "i": "#b3e6ff", "T": "#ccf2ff",
  // Transparent
  ".": "transparent"
};

export const NPC_SPRITES: Record<string, PixelSprite> = {
  "mechanic_01": [
    "..................HHHHHHHHH.....................",
    "................HHHHHHHHHHHHH...................",
    "...............HHHHHHHHHHHHHHH..................",
    "..............HHHHHHHHHHHHHHHHH.................",
    ".............HHHHHhhhhhhhhhhhhH.................",
    "............HHHHHhhhhhhhhhhhhhhH................",
    "............HHHhhhhSSSSSSSSSSShH................",
    "............HHHhhhSSSSSSSSSSSSShH...............",
    "............HHHhhSSSKKKSSSSSKKKSH...............",
    "............HHHhhSSSKWKSSSSSKWKSH...............",
    "............HHHhhSSSSKKSSSSSKKSSH...............",
    "............HHHhhSSSSSSSSSSSSSSSH...............",
    "............HHHhhSSSSSSSSSSSSSSSH...............",
    ".............HHHhhSSSSSSSSSSSSSH................",
    "..............HHHhhSSSSshshsSSSH................",
    "...............HHHHhSSSSSSSSSSHH................",
    "................HHHHHSSSSSSSSHH.................",
    "..................HHHHHHHHHHHH..................",
    "..................WWWWWWWWWWWW..................",
    ".................WWWWWWWWWWWWWW.................",
    "................WWWWWWWWWWWWWWWW................",
    "...............WWWWWWWWWWWWWWWWWW...............",
    "..............WWWWVVVVVVVVVVVVWWWW..............",
    ".............WWWWVVVVVVVVVVVVVVWWWW.............",
    "............WWWWVVVVVVVVVVVVVVVVWWWW............",
    "............WWWWVVVVVVVVVVVVVVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............"
  ],
  "hacker_01": [
    "..................ggggggggg.....................",
    "................ggggggggggggg...................",
    "...............ggggggggggggggg..................",
    "..............ggggggggggggggggg.................",
    ".............gggggAAAAAAAAAAAAg.................",
    "............gggggAAAAAAAAAAAAAAg................",
    "............gggAAAAAAAAAAAAAAAAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASKKKSSSKKSAB................",
    "............gggAAAAASYYKSSSYKSAB................",
    "............gggAAAAASSSKSSSKKSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    ".............gggAAAASSSSSSSSSSAB................",
    "..............gggAAASSSshshsSSAB................",
    "...............gggAASSSSSSSSSSAB................",
    "................ggAASSSSSSSSSSAB................",
    "..................AAAAAAAAAAAAAB................",
    ".................AAAAAAAAAAAAAAB................",
    "................AAAAAAAAAAAAAAAB................",
    "...............AAAAAAAAAAAAAAAAB................",
    "..............AAAAArrrrrrrrrrrAB................",
    ".............AAAAArrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................"
  ],
  "cop_01": [
    "..................KKKKKKKKK.....................",
    "................KKKKKKKKKKKKK...................",
    "...............KKKKKKKKKKKKKKK..................",
    "..............KKKKKKKKKKKKKKKKK.................",
    ".............KKKKKBBBBBBBBBBBBK.................",
    "............KKKKKBBBBBBBBBBBBBBK................",
    "............KKKBBBBBBBBBBBBBBBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSKKSSSKKSBBK................",
    "............KKKBBBBSSRKSSSRKSBBK................",
    "............KKKBBBBSSSKSSSKKSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    ".............KKKBBBSSSSSSSSSSBBK................",
    "..............KKKBBSSSshshsSSBBK................",
    "...............KKBBSSSSSSSSSSBBK................",
    "................KBBSSSSSSSSSSBBK................",
    "..................BBBBBBBBBBBBK.................",
    ".................BBBBBBBBBBBBBB.................",
    "................BBBBBBBBBBBBBBBB................",
    "...............BBBBBBBBBBBBBBBBBB...............",
    "..............BBBBBAAAAAAAAAAABBB...............",
    ".............BBBBBAAAAAAAAAAABBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB..............."
  ]
};

export const PROP_SPRITES: Record<string, PixelSprite> = {
  "vodka_bottle": [
    ".......rrrr.......",
    ".......rrrr.......",
    ".......rrrr.......",
    ".......rrrr.......",
    ".......rrrr.......",
    "......IIIIII......",
    ".....IIIIIIII.....",
    "....IIIIIIIIII....",
    "...IIIIIIIIIIII...",
    "..IIIIIIIIIIIIII..",
    ".IIIIIIIIIIIIIIII.",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIrrrrrrrrIIIII",
    "IIIIrrrrrrrrrrIIII",
    "IIIIrrrrrrrrrrIIII",
    "IIIIIrrrrrrrrIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    "IIIIIIIIIIIIIIIIII",
    ".IIIIIIIIIIIIIIII.",
  ],
  "gin_bottle": [
    ".......llll.......",
    ".......LLLL.......",
    ".......LLLL.......",
    ".......LLLL.......",
    ".......LLLL.......",
    ".......LLLL.......",
    "......LLLLLL......",
    ".....LLLLLLLL.....",
    "....LLLLLLLLLL....",
    "...LLLLLLLLLLLL...",
    "..LLLLLLLLLLLLLL..",
    ".LLLLLLLLLLLLLLLL.",
    "LLLLLLWWWWWWLLLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLWWWWWWWWWWLLLL",
    "LLLLLLWWWWWWLLLLLL",
    "LLLLLLLLLLLLLLLLLL",
    "LLLLLLLLLLLLLLLLLL",
    "LLLLLLLLLLLLLLLLLL",
    "LLLLLLLLLLLLLLLLLL",
    "LLLLLLLLLLLLLLLLLL",
    ".LLLLLLLLLLLLLLLL.",
    "..LLLLLLLLLLLLLL..",
  ],
  "whisky_bottle": [
    "........HH........",
    ".......HHHH.......",
    ".......HHHH.......",
    ".......HHHH.......",
    ".......HHHH.......",
    ".......DDDD.......",
    ".......DDDD.......",
    ".......DDDD.......",
    ".......DDDD.......",
    "......DDDDDD......",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....YYYYYYYY.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    ".....DDDDDDDD.....",
    "......DDDDDD......",
  ],
  "rum_bottle": [
    ".......DDDD.......",
    ".......DDDD.......",
    ".......DDDD.......",
    ".......DDDD.......",
    ".......DDDD.......",
    "......DDDDDD......",
    ".....DDDDDDDD.....",
    "....DDDDDDDDDD....",
    "...DDDDDDDDDDDD...",
    "..DDDDDDDDDDDDDD..",
    ".DDDDDDDDDDDDDDDD.",
    ".DDDDDDDDDDDDDDDD.",
    ".DDDDOOOOOOOOODDD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDOOOOOOOOOOODD.",
    ".DDDDOOOOOOOOODDD.",
    ".DDDDDDDDDDDDDDDD.",
    ".DDDDDDDDDDDDDDDD.",
    "..DDDDDDDDDDDDDD..",
    "...DDDDDDDDDDDD...",
    "....DDDDDDDDDD....",
    ".....DDDDDDDD.....",
    "......DDDDDD......",
  ],
  "ice_bowl": [
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "......II..II......",
    ".....IIIIIIII.....",
    "....IIIIIIIIII....",
    "...WWIIWWIIIIWW...",
    "..WWWWWWWWWWWWWW..",
    ".WWWWWWWWWWWWWWWW.",
    ".WWWWWWWWWWWWWWWW.",
    "..WWWWWWWWWWWWWW..",
    "...WWWWWWWWWWWW...",
    "....WWWWWWWWWW....",
    ".....WWWWWWWW.....",
    "......WWWWWW......",
  ],
  "syrup_bottle": [
    ".......KKKK.......",
    ".......KKKK.......",
    ".......pppp.......",
    ".......pppp.......",
    "......pppppp......",
    ".....pppppppp.....",
    "....pppppppppp....",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...WWWWWWWWWWWW...",
    "...WWWWWWWWWWWW...",
    "...WWWWWWWWWWWW...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "...pppppppppppp...",
    "....pppppppppp....",
  ],
  "lemon_slice": [
    "..................",
    "..................",
    "..................",
    "..................",
    "......YYYYYY......",
    "....YYWWWWWWYY....",
    "...YWWYYYYYYWWY...",
    "..YWWYYYYYYYYWWY..",
    ".YWWYYYWYYWYYYWWY.",
    ".YWWYYYYWWYYYYWWY.",
    ".YWWYYWYYYYWYYWWY.",
    ".YWWYYYYWWYYYYWWY.",
    "..YWWYYYYYYYYWWY..",
    "...YWWYYYYYYWWY...",
    "....YYWWWWWWYY....",
    "......YYYYYY......",
    "..................",
    "..................",
    "..................",
    "..................",
  ],
  "soda_can": [
    "..................",
    "..................",
    "..................",
    "..................",
    "......GGGGGG......",
    ".....G......G.....",
    "....GGGGGGGGGG....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....CCCCCCCCCC....",
    "....GGGGGGGGGG....",
    ".....GGGGGGGG.....",
    "..................",
  ],
  "bitters_bottle": [
    "........KK........",
    ".......KKKK.......",
    ".......KKKK.......",
    ".......KKKK.......",
    "......rrrrrr......",
    ".....rrrrrrrr.....",
    "....rrrrrrrrrr....",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "...WWWWWWWWWWWW...",
    "...WWWWWWWWWWWW...",
    "...WWWWWWWWWWWW...",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "...rrrrrrrrrrrr...",
    "....rrrrrrrrrr....",
    ".....rrrrrrrr.....",
  ],
  "shaker": [
    "........GG........",
    ".......GGGG.......",
    "......GGGGGG......",
    ".....GGGGGGGG.....",
    "....GGGAAAAGGG....",
    "...GGGAAAAAAGGG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "...GGAAAAAAAAAG...",
    "....GGGAAAAGGG....",
    ".....GGGGGGGG.....",
    "......GGGGGG......",
    ".......GGGG.......",
  ],
  "dropper": [
    "........WW........",
    ".......WWWW.......",
    "......WWCCWW......",
    ".....WWCCCCWW.....",
    "....WWCCCCCCWW....",
    "...WWCCCCCCCCWW...",
    "...WWCCCCCCCCWW...",
    "...WWCCCCCCCCWW...",
    "...WWCCCCCCCCWW...",
    "...WWCCCCCCCCWW...",
    "....WWCCCCCCWW....",
    ".....WWCCCCWW.....",
    "......WWCCWW......",
    ".......WWWW.......",
    "........WW........",
    "........WW........",
    "........WW........",
    "........WW........",
    "........WW........",
    "........WW........",
  ],
  "ice_cube": [
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
    "......IIIIII......",
    ".....IIIIIIII.....",
    "....IIIIIIIIII....",
    "....IIIIIIIIII....",
    "....IIIIIIIIII....",
    "....IIIIIIIIII....",
    "....IIIIIIIIII....",
    ".....IIIIIIII.....",
    "......IIIIII......",
    "..................",
    "..................",
    "..................",
    "..................",
    "..................",
  ],
};
