export type PixelSprite = string[];

export const COLOR_MAP: Record<string, string> = {
  // Skin
  "S": "#ffdbac", "s": "#e0ac69", "X": "#8d5524",
  // Hair/Wood
  "h": "#634e34", "H": "#3b2e1e",
  // Red/Pink
  "R": "#ff4d4d", "r": "#cc0000", "p": "#ff73a8",
  // Blue/Cyan
  "B": "#0099ff", "b": "#0066cc", "C": "#73f2ff",
  // Purple
  "P": "#9933ff", "V": "#6600cc",
  // White/Gray
  "W": "#ffffff", "G": "#cccccc", "g": "#888888", "A": "#444444",
  // Yellow/Gold
  "Y": "#ffff4d", "O": "#ffcc00",
  // Black/Dark
  "K": "#1a1a1a", "k": "#0d0d0d",
  // Transparent
  ".": "transparent"
};

export const NPC_SPRITES: Record<string, PixelSprite> = {
  "mechanic_01": [
    "..................HHHHHHHHH.....................",
    "................HHHHHHHHHHHHH...................",
    "...............HHHHHHHHHHHHHHH..................",
    "..............HHHHHHHHHHHHHHHHH.................",
    ".............HHHHHhhhhhhhhhhhhH.................",
    "............HHHHHhhhhhhhhhhhhhhH................",
    "............HHHhhhhSSSSSSSSSSShH................",
    "............HHHhhhSSSSSSSSSSSSShH...............",
    "............HHHhhSSSKKKSSSSSKKKSH...............",
    "............HHHhhSSSKWKSSSSSKWKSH...............",
    "............HHHhhSSSSKKSSSSSKKSSH...............",
    "............HHHhhSSSSSSSSSSSSSSSH...............",
    "............HHHhhSSSSSSSSSSSSSSSH...............",
    ".............HHHhhSSSSSSSSSSSSSH................",
    "..............HHHhhSSSSshshsSSSH................",
    "...............HHHHhSSSSSSSSSSHH................",
    "................HHHHHSSSSSSSSHH.................",
    "..................HHHHHHHHHHHH..................",
    "..................WWWWWWWWWWWW..................",
    ".................WWWWWWWWWWWWWW.................",
    "................WWWWWWWWWWWWWWWW................",
    "...............WWWWWWWWWWWWWWWWWW...............",
    "..............WWWWVVVVVVVVVVVVWWWW..............",
    ".............WWWWVVVVVVVVVVVVVVWWWW.............",
    "............WWWWVVVVVVVVVVVVVVVVWWWW............",
    "............WWWWVVVVVVVVVVVVVVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............",
    "............WWWWVVVKKKKKKKKKKVVVWWWW............"
  ],
  "hacker_01": [
    "..................ggggggggg.....................",
    "................ggggggggggggg...................",
    "...............ggggggggggggggg..................",
    "..............ggggggggggggggggg.................",
    ".............gggggAAAAAAAAAAAAg.................",
    "............gggggAAAAAAAAAAAAAAg................",
    "............gggAAAAAAAAAAAAAAAAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASKKKSSSKKSAB................",
    "............gggAAAAASYYKSSSYKSAB................",
    "............gggAAAAASSSKSSSKKSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    "............gggAAAAASSSSSSSSSSAB................",
    ".............gggAAAASSSSSSSSSSAB................",
    "..............gggAAASSSshshsSSAB................",
    "...............gggAASSSSSSSSSSAB................",
    "................ggAASSSSSSSSSSAB................",
    "..................AAAAAAAAAAAAAB................",
    ".................AAAAAAAAAAAAAAB................",
    "................AAAAAAAAAAAAAAAB................",
    "...............AAAAAAAAAAAAAAAAB................",
    "..............AAAAArrrrrrrrrrrAB................",
    ".............AAAAArrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................",
    "............AAAAArrrrrrrrrrrrrAB................"
  ],
  "cop_01": [
    "..................KKKKKKKKK.....................",
    "................KKKKKKKKKKKKK...................",
    "...............KKKKKKKKKKKKKKK..................",
    "..............KKKKKKKKKKKKKKKKK.................",
    ".............KKKKKBBBBBBBBBBBBK.................",
    "............KKKKKBBBBBBBBBBBBBBK................",
    "............KKKBBBBBBBBBBBBBBBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSKKSSSKKSBBK................",
    "............KKKBBBBSSRKSSSRKSBBK................",
    "............KKKBBBBSSSKSSSKKSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    "............KKKBBBBSSSSSSSSSSBBK................",
    ".............KKKBBBSSSSSSSSSSBBK................",
    "..............KKKBBSSSshshsSSBBK................",
    "...............KKBBSSSSSSSSSSBBK................",
    "................KBBSSSSSSSSSSBBK................",
    "..................BBBBBBBBBBBBK.................",
    ".................BBBBBBBBBBBBBB.................",
    "................BBBBBBBBBBBBBBBB................",
    "...............BBBBBBBBBBBBBBBBBB...............",
    "..............BBBBBAAAAAAAAAAABBB...............",
    ".............BBBBBAAAAAAAAAAABBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB...............",
    "............BBBBBAAAAAAAAAAABBBBB..............."
  ]
};
